### ISSUE TITLE
No podspec found for `EaseUI` in `~/easeui_ios

### ISSUE THREAD

**Issue by mbalex99** [HyphenateInc/Hyphenate-Demo-iOS#2]
When I clone the project and run `pod install`
I get the following error:

`No podspec found for`EaseUI`in`~/easeui_ios`

**Comment by jerrywu12** [comment]
~/easeui_ios is local directory if you have clone the repo locally.
Point to remote repo in podfile using, pod 'EaseUI', :git => 'https://github.com/HyphenateInc/hyphenate-easeui-ios'
