### ISSUE TITLE
Doesn't Compile

### ISSUE THREAD

**Issue by skensell** [HyphenateInc/Hyphenate-Demo-iOS#30]
The current version does not compile after doing `pod install`.  The error message is:

<img width="702" alt="screen shot 2016-12-29 at 1 44 21 pm" src="https://cloud.githubusercontent.com/assets/3983827/21552059/f0b647ac-cdcc-11e6-931f-e62480759876.png">

**Comment by lizilong1989** [comment]
@skensell Please check sdk version when pod install,the latest version is 3.2.2.2

**Comment by skensell** [comment]
okay, after doing `pod repo update` it did eventually work. Just downloading the framework took a really long time (24 minutes):
```
   $ /usr/bin/curl -f -L -o /var/folders/jq/yhhk2nzj2djclbsc95nmd5cm0000gn/T/d20161230-78865-1l2aqtz/file.zip
   http://downloads.easemob.com/downloads/ios_IM_Hyphenate_sdk_3.2.3.zip --create-dirs --netrc-optional
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100 60.6M  100 60.6M    0     0  43116      0  0:24:34  0:24:34 --:--:--  141k
```

**Comment by skensell** [comment]
Also, while I've got your attention, what's the recommended way to integrate the EaseUI.  The guide from the docs suggests integrating from a much older project where the UI is pretty bad IMO.  Is there a suggested way to get the UI from this demo app onto our own apps?  Should I just drag and drop components as necessarry?  Is there a plan to make things like `EMChatViewController` more customizable and available through CocoaPods?
